default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: iron_development

test:
  <<: *default
  database: iron_test

production:
  <<: *default
  database: iron_production
